# fly.toml app configuration file for smartjobcollector
# Generated on 2025-05-30T06:20:00Z
# See https://fly.io/docs/reference/configuration/ for information

app = "smartjobcollector-placeholder" # Replace with your unique app name on Fly.io
primary_region = "iad" # Choose the region closest to you or your users

[build]
  # Specifies the build strategy. Using Dockerfile is recommended for more control.
  # If no Dockerfile is present, Fly.io might attempt to use buildpacks.
  # builder = "paketobuildpacks/builder:base" # Example using buildpacks

# Define the main service that handles HTTP requests
[http_service]
  internal_port = 8080 # The port your app listens on internally
  force_https = true   # Redirect HTTP requests to HTTPS
  auto_stop_machines = true # Stop machines when idle to save costs (Free tier requires this)
  auto_start_machines = true # Start machines automatically when requests come in
  min_machines_running = 0   # Minimum number of machines to keep running (0 for Free tier)
  # IMPORTANT: With auto_stop_machines=true and min_machines_running=0,
  # the background scheduled tasks (node-cron) might not run reliably when the app is idle.
  # Consider Fly Scheduled Machines or upgrading for guaranteed background tasks.

# Define the virtual machine size and type
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 # Smallest available size, suitable for Free tier

# Define environment variables. These should be set as secrets using `flyctl secrets set`.
[env]
  PORT = "8080" # Inform the app to listen on the internal port Fly.io expects
  NODE_ENV = "production"

